const mongoose = require('mongoose');

const bookingSchema = new mongoose.Schema({
  userId: { type: String, required: true },
  
  // Unified identifier (placeId for restaurants/cafes/activities, hotelId for hotels)
  placeId: { type: String, required: true }, 
  placeName: { type: String, required: true },
  
  // Date and Time
  checkIn: { type: Date, required: true }, // Used as booking date for all types
  checkOut: { type: Date },               // Optional for non-hotel bookings
  bookingTime: { type: String },          // Specific time (e.g. "14:00")
  
  // Type of place
  placeType: { 
    type: String, 
    enum: ['hotel', 'restaurant', 'cafe', 'activity', 'attraction'],
    default: 'hotel'
  },

  // Hotel specific (optional)
  mealPlan: {
    type: String,
    enum: ['room_only', 'half_board', 'full_board'],
    default: 'room_only'
  },
  extraServices: [{ type: String }],
  
  // Pricing
  totalPrice: { type: Number, required: true },
  currency: { type: String, default: 'EGP' },
  
  // Payment Info
  paymentMethod: { type: String, default: 'VISA' }, // 'VISA' | 'Wallet' | 'PayOnArrival'
  
  // ── Feature 4: Trip Quality Analysis ─────────────────────────────────────
  // 'manual' = user-initiated booking, 'ai' = generated by AI Trip Planner
  source: { type: String, enum: ['manual', 'ai'], default: 'manual' },
  interestTags: { type: [String], default: [] }, // matched interest keywords for coverage metric
  
  status: {
    type: String,
    enum: ['active', 'pending', 'confirmed', 'cancelled', 'completed', 'reserved'],
    default: 'active'
  }
}, { timestamps: true });

// Backward compatibility virtuals if needed
bookingSchema.virtual('hotelId').get(function() { return this.placeId; });
bookingSchema.virtual('hotelName').get(function() { return this.placeName; });

module.exports = mongoose.model('Booking', bookingSchema);
